name: Deploy to Railway

on:
  push:
    branches:
      - main # Main branch-ə push ediləndə işləsin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Reposu klonla
        uses: actions/checkout@v3

      - name: Node.js quraşdır
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bağımlılıqları yüklə
        run: npm install

      - name: Testləri işə sal (İstəyə bağlı)
        run: npm test || echo "Testlər uğursuz oldu, davam edilir"

      - name: Build yarat
        run: npm run build

      - name: Railway CLI Yükle
        run: npm install -g @railway/cli

      - name: Railway-ə Deploy Et
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
